version: '3.8'

volumes:
  postgres_local_data:

services:
  db:
    container_name: postgres-timeline
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
      - ./scripts/create-db.sql:/create_database.sql
  adminer:
    container_name: adminer-timeline
    image: adminer
    restart: always
    ports:
      - 8080:8080
